ALLOWED_SUBDOMAINS = [
    "Acceptable Use Of Information Technology Resources Policy",
    "Access Control Policy",
    "Account Management Access Control",
    "Auditing And Accountability Policy",
    "Authentication Tokens",
    "Computer Security Threat Response Policy",
    "Configuration Management Policy",
    "Contingency Planning Policy",
    "Cyber Incident Response",
    "Encryption",
    "Identification And Authentication Policy",
    "Incident Response Policy",
    "Information Classification",
    "Information Security Policy",
    "Information Security Risk Management",
    "Maintenance Policy",
    "Media Protection Policy",
    "Mobile Device Security",
    "Patch Management",
    "Personnel Security Policy",
    "Physical And Environmental Protection Policy",
    "Planning Policy",
    "Remote Access",
    "Risk Assessment Policy",
    "Sanitization Secure Disposal",
    "Secure Configuration",
    "Secure System Development Life Cycle",
    "Security Assessment And Authorization Policy",
    "Security Awareness And Training Policy",
    "Security Logging",
    "System And Communications Protection Policy",
    "System And Information Integrity Policy",
    "System And Services Acquisition Policy",
    "Vulnerability Scanning",
]
